springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
server:
  port: 6062
spring:
  application:
    name: auth-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: root
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true