spring:
  application:
    name: student-service
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: root
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true

