spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: root
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true

  redis:
    host: localhost
    port: 6397
    password: ""
    timeout: 60000 # Timeout in milliseconds

  kafka:
    topics:
      student-created: student-created-event
      student-deleted: student-deleted-event
      student-updated: student-updated-event
      student-list: student-list-event
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: student-group


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, mappings, httptrace, env,shutdown
  endpoint:
    health:
      show-details: always
      show-components: always
    httptrace:
      enabled: true
    shutdown:
      enabled: true
logging:
  level:
    root: INFO
    org.springdoc: DEBUG
    org.springframework.web: DEBUG

auth-service-url: http://localhost:6062/auth/v1/user