springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
server:
  port: 6063
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: local
  application:
    name: student-service

upload:
  dir: E:\education-management-app\documents
  max-file-size: 10MB