springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
server:
  port: 6063
spring:
  profiles:
    active: local
  application:
    name: student-service

