server:
  port: 6061
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  application:
    name: gateway-service
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: root
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:6062
          predicates:
           - Path=/auth/**
        - id: student-service
          uri: http://localhost:7071
          predicates:
            - Path=/ems/v1/student/**
          filters:
            - name: CircuitBreaker
              args:
                name: studentServiceCircuitBreaker
                fallbackUri: forward:/studentServiceFallback

  resilience4j.circuitbreaker:
    instances:
      studentServiceCircuitBreaker:
        failureRateThreshold: 50   # 50% failure rate to trigger circuit breaker
        waitDurationInOpenState: 10000ms  # Time to wait before trying half-open state
        slidingWindowSize: 50     # Track more requests for more accurate failure rate
        slidingWindowType: COUNT_BASED
        automaticTransitionFromOpenToHalfOpen: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG

