server:
  port: 6061
spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://localhost:7071
          predicates:
            - Path=/ems/v1/student/**
          filters:
            - name: CircuitBreaker
              args:
                name: studentServiceCircuitBreaker
                fallbackUri: forward:/studentServiceFallback

  resilience4j.circuitbreaker:
    instances:
      studentServiceCircuitBreaker:
        failureRateThreshold: 50   # 50% failure rate to trigger circuit breaker
        waitDurationInOpenState: 10000ms  # Time to wait before trying half-open state
        slidingWindowSize: 50     # Track more requests for more accurate failure rate
        slidingWindowType: COUNT_BASED
        automaticTransitionFromOpenToHalfOpen: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG

